apiVersion: v1
kind: Secret

metadata:
  name: gooddeeds-secret
  namespace: gooddeeds

type: Opaque

stringData:
  POSTGRES_PASSWORD: postgres
  JWT_SECRET_KEY: GoodDeedsJwtSecret@2026
  SECRET_KEY: GoodDeedsAppSecret@2026
  FIRST_ADMIN_PASSWORD: GoodDeedsAdmin@2026
