apiVersion: apps/v1
kind: Deployment

metadata:
  name: gooddeeds-api
  namespace: gooddeeds

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gooddeeds-api

  template:
    metadata:
      labels:
        app: gooddeeds-api

    spec:
      containers:
      - name: gooddeeds-api

        image: gooddeeds-api:v2

        imagePullPolicy: Never

        ports:
        - containerPort: 8000

        env:
        - name: DATABASE_URL
          value: postgresql+asyncpg://postgres:postgres@postgres-service:5432/gooddeed_db

        - name: REDIS_URL
          value: redis://redis-service:6379/0

        envFrom:
        - secretRef:
            name: gooddeeds-secret

        - configMapRef:
            name: gooddeeds-config
